# Generated by Django 3.0.8 on 2020-08-20 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20200813_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='paid_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
