# Generated by Django 3.0.8 on 2020-08-24 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_userprofile_paid_until'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='paid_until',
        ),
    ]
