# Generated by Django 3.0.8 on 2020-08-17 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programs',
            options={'verbose_name_plural': 'Programs'},
        ),
        migrations.AddField(
            model_name='programs',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
    ]
