# Generated by Django 3.0.8 on 2020-08-19 20:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_programs_post_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programs',
            options={'ordering': ('-pk',), 'verbose_name_plural': 'Programs'},
        ),
        migrations.AlterField(
            model_name='programs',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
