# Generated by Django 3.0.8 on 2020-08-19 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0005_programs_snippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='programs',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='programs',
            name='header_image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
