# Generated by Django 3.0.8 on 2020-08-20 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0007_auto_20200820_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='price_annual',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
