# Generated by Django 3.0.8 on 2020-08-24 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0008_category_price_annual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.RemoveField(
            model_name='category',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='category',
            name='price',
        ),
        migrations.RemoveField(
            model_name='category',
            name='price_annual',
        ),
        migrations.RemoveField(
            model_name='programs',
            name='is_free',
        ),
    ]
