# Generated by Django 3.0.8 on 2020-07-30 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product_detail',
            options={'verbose_name': 'Product Detail'},
        ),
        migrations.AddField(
            model_name='product_detail',
            name='prod_id',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
