# Generated by Django 3.0.8 on 2020-08-27 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200816_1309'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('pk',)},
        ),
    ]
